modelmapper/modelmapper

core/src/main/java/org/modelmapper/internal/converter/CollectionConverter.java, core/src/test/java/org/modelmapper/internal/converter/CollectionConverterTest.java
Previously the CollectionConverter was only discriminating between Lists and
Sets, instanciating an ArrayList if the destination type was a List and a
HashSet if the destination type was a Set. This failed when the destination
type was a SortedSet (HashSet is not a SortedSet).
Rather than change the HashSet to a TereSet for all Sets, a separate check has
been added for SortedSets so that the more performant HashMap is still used
generally and a TreeSet is used only when we know we need a SortedSet.
Two test cases where added. One is to test that the SortedSet mapping works.
The other is to test that HashSets are still used when a SortedSet is not
requested. This second test may not be necessary if we don't care that much
about the implementation backing the mapped property.
=> Add support for mapping to SortedSets destinations.

core/src/main/java/org/modelmapper/convention/InexactMatcher.java, core/src/test/java/org/modelmapper/bugs/GH143.java
Hi. I started using ModelMapper one hour ago and found what looks like a bug. At first I thought I was not naming things right, but after digging a bit with the debugger I found this:
In a `Map` I have a property named `"__rid"` (comes from a db column name), and am using an underscore tokenizer. At some point in `InexactMatcher.matchTokens` the `src` array is `["","","rid"]`, so `srcStr.charAt(0)` throws the exception.
At this moment I am not sure how to run the test suite and what the convention of writing tests is. I just need this quick fix for myself for now.
Please let me know if it looks reasonable and if you need more help from my part.
Thank you for this excellent library.
=> Prevent StringIndexOutOfBoundsException

core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java, core/src/test/java/org/modelmapper/bugs/GH176.java
This fixes GH176. It is not the optimal solution, but all tests passes, including GH26, which seems to be somewhat related. The optimal solution would of course be to not call the private constructor.
https://github.com/jhalterman/modelmapper/issues/176
=> GH176 Reuse of converters

core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java, core/src/test/java/org/modelmapper/bugs/GH153.java
Resolved #153
**Reason**
At [ExplicitMappingVisitor.java#L202](https://github.com/jhalterman/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java#L202)
```java
if (mapType != 0 && !isAccessor(mn) && mn.owner.equals(lastMutatorOwner)) {
recordDestinationMethod(ownerType, methodFor(ownerType, methodType, mn));
recordProperties();
}
```
It determine current method is last destination or not by check
- not isAccessor
- the owner of the method is equal to destination type
The second part want to make sure that the method is from destination not from the source,
but it let PropertyMap which had define parent class or interface as its destination type would failed on determine last destination mutator.
So I try following modification and it seems that …
=> Resolved #153: update the logic for determine when last destination mutator hit

core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java, core/src/test/java/org/modelmapper/bugs/GH197.java
Ref: #197 
When used PropertyMap with ```when(condition).skip().setA(source.getA())```,
The field ```a``` will be skipped even condition not match.
That's not an expected behavior of modelmapper.
@AUsachov could you help me verify that the bug is fixed by this PR? Thanks!
=> Fix bug modelmapper skip path problem

core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java, core/src/main/java/org/modelmapper/internal/PropertyInfoRegistry.java, core/src/test/java/org/modelmapper/bugs/GH204.java
Currently, we found that when getter/setter had same
method name, then they will have same hash code when
we cache them. Then we had the risk for getting a
mutator when we try getting an accessor.
So I separate mutator, accessor, and field into three
different cache
=> Resolved #204: getting wrong type in PropertyInfoRegistry cache

core/src/main/java/org/modelmapper/ExpressionMap.java, core/src/main/java/org/modelmapper/TypeMap.java, core/src/main/java/org/modelmapper/builder/ConfigurableMapExpression.java, core/src/main/java/org/modelmapper/builder/ReferenceMapExpression.java, core/src/main/java/org/modelmapper/internal/ConfigurableMapExpressionImpl.java, core/src/main/java/org/modelmapper/internal/PropertyReferenceCollector.java, core/src/main/java/org/modelmapper/internal/ReferenceMapExpressionImpl.java, core/src/main/java/org/modelmapper/internal/TypeMapImpl.java, core/src/main/java/org/modelmapper/internal/TypeMapStore.java, core/src/main/java/org/modelmapper/spi/DestinationSetter.java, core/src/main/java/org/modelmapper/spi/SourceGetter.java, core/src/test/java/org/modelmapper/functional/lambda/TypeMapLambdaDeepMapTest.java, core/src/test/java/org/modelmapper/functional/lambda/TypeMapLambdaMultipleFieldsTest.java, core/src/test/java/org/modelmapper/functional/lambda/TypeMapLambdaTest.java, core/src/test/java/org/modelmapper/functional/lambda/TypeMapLambdaTypeConvertTest.java
Provide lambda friendly api
The demo please reference [Unit Test](https://github.com/chhsiao90/modelmapper/blob/lambda-demo/misc/misc-lambda/src/test/java/org/modelmapper/misc/lambda/TypeMapTest.java)
```java
typeMap.addMapping(Src::getA, Dest::setB);
typeMap.addMapping(src -> src.getA().getB(), dest, v -> dest.getC().setD(v));
```
You can do like this
```java
typeMap.addMappings(mapping -> mapping.with(provider).map(Src::getA, Dest::setB));
typeMap.addMappings(mapping -> mapping.using(converter).map(Src::getA, Dest::setB));
typeMap.addMappings(mapping -> mapping.when(condition).map(Src::getA, Dest::setB));
typeMap.addMappings(mapping -> mapping.skip(Dest::setB));
```
or like this
```java
typeMap.addMappings(mapping -> {
mapping.with(provider).map(Src::getA, Dest::setB); …
```
=> Lambda friendly API

core/src/main/java/org/modelmapper/TypeMap.java, core/src/main/java/org/modelmapper/internal/TypeMapImpl.java, core/src/main/java/org/modelmapper/internal/TypeMapStore.java, core/src/test/java/org/modelmapper/functional/inherit/MultipleInterfacesTest.java, core/src/test/java/org/modelmapper/functional/inherit/TypeMapIncludeBaseTest.java, core/src/test/java/org/modelmapper/functional/inherit/TypeMapIncludeTest.java, core/src/test/java/org/modelmapper/functional/inherit/TypeMapInheritanceDeepTypeTest.java, core/src/test/java/org/modelmapper/functional/inherit/ValueReaderInheritanceTest.java
Related: #13 #130 #132 #170 #202 
A better solution than #208
After that, TypeMap provide ```include``` and ```includeBase``` for inheritance
```
TypeMap<SrcInterface, DestInterface> baseTypeMap =
modelMapper.addMappings(new PropertyMap<SrcInterface, DestInterface>() {
@Override
protected void configure() {
map().setDest(source.getSrc());
}
});
baseTypeMap.include(SrcA.class, DestA.class)
.include(SrcB.class, DestB.class);
.include(SrcC.class, DestC.class);
```
```
modelMapper.addMappings(new PropertyMap<SrcInterface, DestInterface>() {
@Override
protected void configure() {
map().setDest(source.getSrc());
}
});
modelMapper.createTypeMap(SrcA.class, DestA.class).includeBase(SrcInterface.class, DestInterface.class);
modelMapper.createTypeMap(SrcB.class, …
```
=> TypeMap inheritance

core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java, core/src/main/java/org/modelmapper/internal/util/Types.java
Because of single responsibility and code reusability, moved
method classFor(asmType) to an internal util class Types
=> Relocate method: classFor(asmType) to Types

core/src/main/java/org/modelmapper/internal/Accessor.java, core/src/main/java/org/modelmapper/internal/ImplicitMappingBuilder.java, core/src/main/java/org/modelmapper/internal/InternalPropertyInfo.java, core/src/main/java/org/modelmapper/internal/Mutator.java, core/src/main/java/org/modelmapper/internal/PropertyInfoImpl.java, core/src/main/java/org/modelmapper/internal/PropertyInfoSetResolver.java, core/src/main/java/org/modelmapper/internal/TypeInfoRegistry.java, core/src/main/java/org/modelmapper/internal/TypeMapImpl.java, core/src/main/java/org/modelmapper/internal/TypeMapStore.java, core/src/main/java/org/modelmapper/internal/util/Types.java, core/src/main/java/org/modelmapper/internal/valueaccess/MapValueReader.java, core/src/main/java/org/modelmapper/spi/ValueReader.java, core/src/test/java/org/modelmapper/TypeMapTest.java, core/src/test/java/org/modelmapper/functional/deepmapping/DeepMappingTest1.java, core/src/test/java/org/modelmapper/functional/deepmapping/NestedMappingTest2.java, core/src/test/java/org/modelmapper/internal/MatchingStrategyTestSupport.java, core/src/test/java/org/modelmapper/internal/valueaccess/MapValueReaderTest.java, extensions/gson/src/main/java/org/modelmapper/gson/JsonElementValueReader.java, extensions/gson/src/test/java/org/modelmapper/gson/JsonElementValueReaderTest.java, extensions/jackson/src/main/java/org/modelmapper/jackson/JsonNodeValueReader.java, extensions/jackson/src/test/java/org/modelmapper/jackson/JsonNodeValueReaderTest.java, extensions/jooq/src/main/java/org/modelmapper/jooq/RecordValueReader.java, extensions/jooq/src/test/java/org/modelmapper/jooq/RecordValueReaderTest.java
Resolved:
#118 #133 #137 #168 #186 #188 #194
ValueReader should have two functionality.
One is at TypeMap building time (by ImplicitMappingBuilder), that it need to get accessors to build mappings in the TypeMap.
Another one is after TypeMap built, ModelMapper need to get the destination value.
So I think it would be better to separate into two methods.
- Introduce new class ValueAccessor, so that we won't expose internal class/method
- Implement JSON/JOOQ/MAP ValueReader#getAccessor
Currently, we had problem on mapping dynamic type is that we always cache the TypeMap into TypeMapStore, even it was incomplete.
So I think we solution to solve the root cause, is that we don't save the wrong TypeMap into TypeMapStore, till the mappings ins TypeMap is completed.
- Check is completed or not …
=> Resolved ValueReader handling null value problem

core/src/main/java/org/modelmapper/TypeMap.java, core/src/main/java/org/modelmapper/builder/ReferenceMapExpression.java, core/src/main/java/org/modelmapper/internal/ConfigurableMapExpressionImpl.java, core/src/main/java/org/modelmapper/internal/ReferenceMapExpressionImpl.java, core/src/main/java/org/modelmapper/internal/TypeMapImpl.java
We don't need to explicit define the setter's value type when defining
expression mapping, so we removed it!
=> Remove unneeded generic types

core/src/main/java/org/modelmapper/ModelMapper.java, core/src/test/java/org/modelmapper/ModelMapperTest.java
Provides a shortcut for create or get a TypeMap in a ModelMapper
Closed: #214
=> Introduce ModelMapper.typeMap()

core/src/main/java/org/modelmapper/convention/InexactMatcher.java, core/src/test/java/org/modelmapper/bugs/GH234.java, core/src/test/java/org/modelmapper/convention/InexactMatcherTest.java
When source property tokens contains similar destination property token,
the matcher seams will skip matching process even there is a full match
token exist. For instance, with given destination property token: go, it
will failed to find matched token with given source tokens: goo, go.
Closed: #234
=> Fix field matching bug

core/src/main/java/org/modelmapper/config/Configuration.java, core/src/main/java/org/modelmapper/internal/InheritingConfiguration.java, core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java, core/src/test/java/org/modelmapper/functional/skip/EnableSkipNullTest.java
Sometimes we don't want to map a null value to be set into
destination property, so we provide an option to configure
whether we should skip mapping null value to destination
property or not.
Resolved: #217
=> Add a configuration option: skipNull

core/src/main/java/org/modelmapper/internal/ExplicitMappingBuilder.java, core/src/main/java/org/modelmapper/internal/PropertyReferenceCollector.java, core/src/main/java/org/modelmapper/internal/ReferenceMapExpressionImpl.java, core/src/test/java/org/modelmapper/functional/enums/EnumSetMappingTest.java
We try to proxy all properties when user build an explicit map,
but we cannot proxy some class with cglib like EnumSet. But for
some case, we don't need to proxy all properties, so we try to
return null instead of throw error instantly. And we throw errors
when we got NullPointerException.
Resolved: #260
=> Returns null instead of throw error for ProxyClass

core/pom.xml, core/src/main/java/org/modelmapper/config/Configuration.java, core/src/main/java/org/modelmapper/internal/BridgeClassLoaderFactory.java, core/src/main/java/org/modelmapper/internal/ExplicitMappingBuilder.java, core/src/main/java/org/modelmapper/internal/InheritingConfiguration.java, core/src/main/java/org/modelmapper/internal/ProxyFactory.java
Creating a new PR on top of my first one:
https://github.com/modelmapper/modelmapper/pull/286
The idea here is to apply the OSGi Class Loader Bridge approach that is described here:
https://www.infoq.com/articles/code-generation-with-osgi
This eliminates the need to define explicit OSGi imports to the cglib classes in user's bundles.
In addition to that, it attempts to solve the issue described here:
https://stackoverflow.com/questions/47854086/cglib-creating-class-proxy-in-osgi-results-in-noclassdeffounderror
The idea is to keep track of class loaders of class types that are found in the parent type hierarchy of the user's type. We can later use these class loaders as fallback for loading types that are otherwise unknown to the Bundle's class loader of the user's type.
=> OSGi class loader bridge

core/src/main/java/org/modelmapper/internal/converter/NumberConverter.java, core/src/test/java/org/modelmapper/internal/converter/NumberConverterTest.java
It would be nice feature to convert the `XMLGregorianCalendar` to `Long` time from epoch milliseconds as the `CalendarConverter` do. 
Because the `modelmapper` uses the first converter to convert the field, the `NumberConverter` will do this and currently it throws an exception, because it tries to call `numberFor(source.toString(), destinationType)`
=> XMLGregorianCalendar to Long converter

core/src/main/java/org/modelmapper/ModelMapper.java
The objective here is to skip the type inference in cases we already know the types.
I'm using this to create a new spring boot starter with almost zero config by detecting Entities 
and register simple generic converters.
=> Add converter method with explicit types

core/pom.xml, core/src/main/java/org/modelmapper/internal/ProxyFactory.java
Bump up library dependencies for
1) ByteBuddy from 1.8.3 to 1.8.22
2) ASM       from 6.1.1 to 6.2.1
3) Cglib     from 3.2.6 to 3.2.8
Also added usage of `ClassLoadingStrategy` for `load()` method when using
ByteBuddy, which is recommended by the author of the ByteBuddy library
here: https://github.com/raphw/byte-buddy/issues/447
=> In order to use ModelMapper in jdk11 (build 11+28).

core/pom.xml
Reverted the change to the build introduced by f0202484806ff039cb7ffbd24cfd3da58480c009 to execute the bundle plugin on the unpacked shaded jar to ensure all classes including internal are examined for imports by the bnd plugin.
=> Fix OSGI Imports required by internal packages: Fixes(#401)

core/pom.xml
Use Embed-Dependency directive of maven bundle plugin to calculate imports of third party dependencies and avoid twice execution of maven plugin.
Remove excludes from bytebuddy in favor of dependency management.
```Manifest-Version: 1.0
Bnd-LastModified: 1538390489756
Build-Jdk: 1.8.0_101
Bundle-Description: Simple, Intelligent, Object Mapping
Bundle-License: http://apache.org/licenses/LICENSE-2.0
Bundle-ManifestVersion: 2
Bundle-Name: ModelMapper
Bundle-SymbolicName: modelmapper
Bundle-Version: 2.3.1.SNAPSHOT
Created-By: Apache Maven Bundle Plugin
Embed-Dependency: *;scope=runtime;inline=true
Export-Package: org.modelmapper;uses:="org.modelmapper.builder,org.model
mapper.config,org.modelmapper.spi";version="2.3.1",org.modelmapper.buil …
```
=> Mark com.misc as optional dependencies in MANIFEST.MF

core/src/main/java/org/modelmapper/internal/util/Iterables.java, core/src/test/java/org/modelmapper/internal/util/IterablesTest.java
Hello,
I have recently found, that when you try to map elements from collection, which does not implement List interface, into another this raises NoSuchElementBug. It happens in the below fragment:
```
public static Object getElementFromCollection(Collection<Object> collection, int index) {
if (collection.size() < index + 1)
return null;
if (collection instanceof List)
return ((List<Object>) collection).get(index);
Iterator<Object> iterator = collection.iterator();
for (int i = 0; i <= index; i++) {
iterator.next();
}
return iterator.next();
}
```
This method, when called with HashSet containing only one element and index=0 throws NoSuchElementException because it calls `iterator.next();` too many times. I have stumbled upon this bug when trying to map one Set to another, like that:
``` …
```
=> Fix NoSuchElementException when iterating through Collection interface using iterator

core/src/main/java/org/modelmapper/internal/PropertyInfoRegistry.java, core/src/test/java/org/modelmapper/internal/PropertyInfoRegistryTest.java
ModelMapper sometimes tries to map wrong property. I logged `TypeMapStore`'s `typeMaps` field and it looks as follows.
```
...
codehumane.Source -> codehumane.Destination
PropertyMapping[Source.name -> Destination.name]
PropertyMapping[Source.age -> Destination.age]
PropertyMapping[Hello.hi -> Destination.sex] // invalid mapping here!
PropertyMapping[Source.phone -> Destination.phone]
...
```
I looked a little further and I think `PropertyInfoRegistry#hashCodeFor` is the problem.
1. Sometimes `hashCodeFor` returns same value for different properties.
2. Then `PropertyInfoRegistry` stores just one property and ignores others.
So, I create `PropertyInfoKey` to use as a cache key instead of `Integer` to resolve hash collision.
All tests are green. And I hope this is all right. Thanks!
=> Fixed invalid property info return on hash collision

core/src/main/java/org/modelmapper/config/Configuration.java, core/src/main/java/org/modelmapper/internal/InheritingConfiguration.java, core/src/main/java/org/modelmapper/internal/converter/ConverterStore.java, core/src/main/java/org/modelmapper/internal/converter/MergingCollectionConverter.java, core/src/main/java/org/modelmapper/internal/converter/NonMergingCollectionConverter.java, core/src/test/java/org/modelmapper/internal/converter/MergingCollectionConverterTest.java, core/src/test/java/org/modelmapper/internal/converter/NonMergingCollectionConverterTest.java
ModelMapper may be used for DTO <-> Entity mapping in web service applications and is even suggested to be used for that by tutorials (i.e. https://www.baeldung.com/entity-to-and-from-dto-for-a-java-spring-application).
The current behavior of the `CollectionConverter` is not expected in such a use-case as it preserves the elements in the destination collection when the source collection is smaller, refer to #423 and #386.
This pull request 
- adds a new converter, the `NonMergingCollectionConverter`,
- renames the existing `CollectionConverter` to `MergingCollectionConverter`, 
- adds a configuration option to the `Configuration` interface,
- sets the current `CollectionConverter`, now the `MergingCollectionConverter` as default and 
- adjusts the `InheritingConfiguration` accordingly.
=> Add non-merging collection converter and configuration option to use one or the other

core/src/main/java/org/modelmapper/internal/util/Types.java
Hi.
I have added simple support for `HibernateProxy` instances. I don't know if further enhancement is needed. Please let me know.
Like the author of https://github.com/modelmapper/modelmapper/issues/442 I am experiencing the same issues and must unproxy Hibernate managed entities to map them to domain classes using ModelMapper.
=> Cannot detect Hibernate proxy classes

core/src/main/java/org/modelmapper/internal/InheritingConfiguration.java, core/src/main/java/org/modelmapper/internal/converter/ConverterStore.java, core/src/test/java/org/modelmapper/functional/config/DeepCopyEnabledTest.java, core/src/test/java/org/modelmapper/internal/converter/MergingCollectionConverterTest.java
This PR demostrate with a test case that if I change the default configuration of merge collection strategy I'm not able to map a `Collection<S>` into `Collection<D>` anymore. The result will be always a `Collection<S>`.
`modelMapper.map(listOfS, new org.modelmapper.TypeToken<List <D>>() {}.getType())` return listOfS instance.
The issue happens because when the configuration is changed the MergingCollectionConverter is moved from position 1 in the list of converters in the converterStore as the latest conveter. Maybe some other converter takes over and the `MergingCollectionConverter.convert(MappingContext<Object, Collection<Object>> context)` is never called.
To solve the issue the MergingCollectionConverter should be added again the same position as before. Or change the conveters list …
=> Change collections merge strategy breaks collection mapping

core/src/main/java/org/modelmapper/internal/converter/MapConverter.java, core/src/test/java/org/modelmapper/internal/converter/MapConverterTest.java
Allow mapping of generic map types with TypeToken:
```
Map<Integer, BigDecimal> numbers = Collections.singletonMap(1, BigDecimal.valueOf(2));
Type mapType = new org.modelmapper.TypeToken<Map<Long, String>>() {}.getType();
Map<Long, String> mixed =  new ModelMapper().map(numbers, mapType);
```
=> allow mapping of generic map types

core/pom.xml
Update typetools to version 0.6.2 to better support jdk11
=> Update typetools to 0.6.2

core/src/main/java/org/modelmapper/internal/ProxyFactory.java
This is regarding issue #482.
After debugging I think I've found that the problem seems to arise due to the renaming of the "net.bytebuddy" package to "org.modelmapper.internal.bytebuddy" when using the maven-shade-plugin on modelmapper's core pom.xml (line 128).
This also renames the `BYTE_BUDDY_RENAME_PACKAGE` constant on `net.bytebuddy.NamingStrategy.SuffixingRandom` that is used on the `ByteBuddy` constructor to be used as `namingStrategy` from **net.bytebuddy.renamed** to **org.modelmapper.internal.bytebuddy.renamed**.
This makes that on proxy generation on `org.modelmapper.internal.ProxyFactory#proxyFor(java.lang.Class<T>, java.lang.reflect.InvocationHandler, org.modelmapper.internal.Errors, boolean)` the exception mentioned on the issue to be thrown.
The way I've tried to fix it …
=> Try to fix IllegalArgumentException due to package renaming

core/pom.xml
This increases the asm version to version 9, the current one and fixes the problem described in [Issue 564](https://github.com/modelmapper/modelmapper/issues/564). 
I can provide a small POC project to demonstrate a) the problem and b) that it's resolved by this.
=> #564 - Bump ASM to version 9

core/src/main/java/org/modelmapper/internal/ProxyFactory.java
Jdk 9 and newer JDK display warning messages while we are trying to
proxy a java colleciton type java collection type. To fix this issue,
we just return null when we are proxy a collection type, because it's
useless to proxy a collection while defining an explicit mapping,
Resolved: #414
=> Eliminate warnings while defining explicit mapping on collections

core/src/main/java/org/modelmapper/internal/ConfigurableConditionExpressionImpl.java, core/src/main/java/org/modelmapper/internal/ExplicitMappingBuilder.java, core/src/main/java/org/modelmapper/internal/PropertyReferenceCollector.java, core/src/main/java/org/modelmapper/internal/ProxyFactory.java, core/src/main/java/org/modelmapper/internal/ReferenceMapExpressionImpl.java
Reflections are slow, reduces the calls can speed up modelmapper.
Resolved: #462
=>  Reduces redundant proxy to speed up setup explicit mappings

core/src/main/java/org/modelmapper/internal/TypeMapStore.java, core/src/test/java/org/modelmapper/functional/enums/EnumWithAnonymousClassMapTest.java
When the source of mapping is an instance of an enum with some methods overridden, the source is essentially an extension anonymous class of an original enum. For such sources, type map lookup doesn't return the desired instance. It leads to unexpected mapping results. 
Please see the test case at
https://github.com/modelmapper/modelmapper/pull/617/commits/3bebc4e0616694b701e0449ee2b743b838d0c34f#diff-7bb3714c07d31f0e6def4190141b1fcd3a7a2cdb1b2a8bee81f17b6a1550a73dR11
=> Type map store lookup fix for enums with anonymous class

benchmarks/pom.xml, benchmarks/src/main/java/org/modelmapper/benchmarks/GiantModelBenchmark.java, benchmarks/src/main/java/org/modelmapper/benchmarks/Main.java, benchmarks/src/main/java/org/modelmapper/benchmarks/model/GiantDto.java, benchmarks/src/main/java/org/modelmapper/benchmarks/model/GiantEntity.java, benchmarks/src/main/java/org/modelmapper/benchmarks/model/GiantFieldDto.java, benchmarks/src/main/java/org/modelmapper/benchmarks/model/GiantFieldEntity.java, core/src/main/java/org/modelmapper/ModelMapper.java, core/src/main/java/org/modelmapper/internal/PropertyInfoImpl.java, core/src/main/java/org/modelmapper/internal/PropertyNameInfoImpl.java, core/src/main/java/org/modelmapper/internal/TypeMapStore.java, core/src/main/java/org/modelmapper/internal/TypeResolvingList.java, pom.xml
Resolved: #618 
Before
```
Benchmark                             Mode  Cnt    Score    Error  Units
GiantModelBenchmark.measure          thrpt    5  170.129 ± 18.995  ops/s
GiantModelBenchmark.measureSubclass  thrpt    5  158.574 ± 24.168  ops/s
```
After
```
Benchmark                             Mode  Cnt    Score     Error  Units
GiantModelBenchmark.measure          thrpt    5  856.024 ±  25.241  ops/s
GiantModelBenchmark.measureSubclass  thrpt    5  897.057 ± 117.059  ops/s
```
=> Improve performance on implicit mapping

pom.xml
Our project is using Java 18 and we have tried to upgrade it to Java 19.
The code compiled properly, but the modules using the ModelMapper dependency began to fail in runtime with the following message:
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63 at org.modelmapper.internal.asm.ClassReader.<init>(ClassReader.java:199)
The `org.modelmapper.internal.asm.ClassReader` class mentioned above comes from the `asm-tree` library (`org.objectweb.asm` is shaded by the `maven-shade-plugin` configured in ModelMapper).
The update of the `asm-tree` library to the latest version `9.4` seems to solve the issue: it compiles properly and there are no more runtime failures.
=> Compatibility with Java 19

core/src/main/java/org/modelmapper/internal/util/Types.java
I have a project using [Permazen](https://github.com/permazen/permazen) ORM. _ModelMapper_ does not recognize permazen's proxies. It's just the matter of two strings addition in `Types` utility class to support these. I realize that _Permazen ORM_ is rarely used, but appreciate if you'll accept this small PR.
=> Add support for Permazen proxies

core/src/test/java/org/modelmapper/internal/TypeInfoImplTest.java, core/src/test/java/org/modelmapper/internal/converter/ArrayConverterTest.java
The tests below were found flaky because of the ordering of `HashSets` and `HashMaps`. The orders of elements in the HashSets and HashMaps are not the same every time the test being called. In this case, `HashSet` is changed into `LinkedHashSet`, and the unordered results from `HashMap` are sorted for comparing. This code change is trying to fix the [flaky tests](https://docs.gitlab.com/ee/development/testing_guide/flaky_tests.html) mentioned above, because they sometimes fail (as the picture showed) and sometimes pass when comparing the strings. The failure could be reproduced by the commands above by using the tool of [NonDex](https://github.com/TestingResearchIllinois/NonDex). The code change is to make sure the tests will always pass in this case.
- …
=> Fix flaky tests caused by nondeterministic of HashSets and HashMaps

pom.xml
The versions of ByteBuddy and ASM were changed for the latest ones that supports Java 23.
Best regards
=> Support Java 23

core/src/main/java/org/modelmapper/internal/util/Types.java
As a result of this change in Hibernate:
https://hibernate.atlassian.net/browse/HHH-14694
The hibernate proxy class names no longer have a `$` at the end, and so this `isProxied` check fails, resulting in the typeMap not being properly fetched and some mapping errors. 
Here is a screenshot of the class name when using hibernate 6.6.12 and above:
=> Fix Hibernate proxy issue

core/pom.xml
This PR excludes META-INF/versions/** folders from shaded dependencies (such as Byte Buddy).
See https://github.com/raphw/byte-buddy?tab=readme-ov-file#dependency-and-api-evolution
for official recommendation.
Fixes #770
=> Filter out META-INF/versions/** from shaded dependencies
