core/pom.xml

add reflect-package to cglib-shadow

---

core/src/main/java/org/modelmapper/internal/util/Members.java
core/src/test/java/org/modelmapper/internal/util/MembersTest.java

fix mapping of properties defined in super-interfaces

---

core/src/main/java/org/modelmapper/internal/Errors.java

Fix NullPointerException in Erros.Converter.appliesTo

---

core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java
core/src/main/java/org/modelmapper/internal/util/Primitives.java
core/src/test/java/org/modelmapper/bugs/GH220.java

Fixed ASM type resolver to resolve non-primitive array type correctly.
Resolved #220

Resolve ASM type correctly

---

core/src/main/java/org/modelmapper/TypeMap.java
core/src/main/java/org/modelmapper/builder/ReferenceMapExpression.java
core/src/main/java/org/modelmapper/internal/ConfigurableMapExpressionImpl.java
core/src/main/java/org/modelmapper/internal/ReferenceMapExpressionImpl.java
core/src/main/java/org/modelmapper/internal/TypeMapImpl.java

Reverts modelmapper/modelmapper#232
It didn't help... We actually need the destination value's type..

Revert "Remove unneeded generic types"

---

core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java
core/src/test/java/org/modelmapper/bugs/GH171.java

Provided destination property was not passed to sub TypeMap.
Check destination before invoke TypeMap mappings to make sure
the provided destination will not disappear.
Closed: #171

Keep provided destination property to sub type map

---

core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java
core/src/test/java/org/modelmapper/bugs/GH249.java

Fixed NPE when getting destination property

---

core/src/main/java/org/modelmapper/internal/valueaccess/MapValueReader.java
core/src/test/java/org/modelmapper/internal/valueaccess/MapValueReaderTest.java
extensions/gson/src/main/java/org/modelmapper/gson/JsonElementValueReader.java
extensions/jackson/src/main/java/org/modelmapper/jackson/JsonNodeValueReader.java

Returns null when read inexist value in ValueReader

---

core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java
core/src/test/java/org/modelmapper/bugs/GH267.java

The propertyCondition will not be used by skip

---

core/src/main/java/org/modelmapper/internal/PropertyReferenceCollector.java
core/src/main/java/org/modelmapper/internal/ProxyFactory.java
core/src/main/java/org/modelmapper/internal/ReferenceMapExpressionImpl.java
core/src/test/java/org/modelmapper/bugs/GH287.java

Throws ConfigurationException instead of NullPointerException

---

core/src/main/java/org/modelmapper/internal/ImplicitMappingBuilder.java
core/src/test/java/org/modelmapper/bugs/GH283.java

Should not traversal destination property if already have a TypeMap

---

core/src/main/java/org/modelmapper/internal/TypeMapStore.java
core/src/test/java/org/modelmapper/bugs/GH291.java

Also checked primitive wrapper for TypeMap

---

core/src/main/java/org/modelmapper/ModelMapper.java
core/src/main/java/org/modelmapper/Module.java

Adds module to support customize extensions

---

core/src/main/java/org/modelmapper/internal/MappingImpl.java
core/src/main/java/org/modelmapper/internal/PropertyMappingImpl.java
core/src/main/java/org/modelmapper/internal/SourceMappingImpl.java
core/src/test/java/org/modelmapper/functional/converter/ConvertNestedObjectTest.java

This issue was caused by the wrong logic of creating merged mappings of source mapping.
Resolved: #331

Fixes nested convert failure when using source mapping

---

extensions/jackson/src/main/java/org/modelmapper/jackson/ArrayNodeConverter.java
extensions/jackson/src/main/java/org/modelmapper/jackson/JacksonModule.java
extensions/jackson/src/test/java/org/modelmapper/jackson/JsonArrayTest.java

Implements jackson module and handle with ArrayNode

---

core/src/main/java/org/modelmapper/TypeMap.java
core/src/main/java/org/modelmapper/internal/ExplicitMappingBuilder.java
core/src/main/java/org/modelmapper/internal/ImplicitMappingBuilder.java
core/src/main/java/org/modelmapper/internal/TypeMapImpl.java
core/src/main/java/org/modelmapper/internal/TypeMapStore.java
core/src/test/java/org/modelmapper/bugs/GH336.java

[WIP] Implement perform implicit mapping on TypeMap

---

core/src/main/java/org/modelmapper/config/Configuration.java
core/src/main/java/org/modelmapper/internal/InheritingConfiguration.java
core/src/main/java/org/modelmapper/internal/converter/ConverterStore.java

Provides configuration: deepCopyEnabled

---

core/src/main/java/org/modelmapper/internal/PropertyReferenceCollector.java
core/src/main/java/org/modelmapper/internal/ProxyFactory.java
core/src/main/java/org/modelmapper/internal/ReferenceMapExpressionImpl.java
core/src/test/java/org/modelmapper/functional/lambda/TypeMapLambdaFromConstantTest.java
core/src/test/java/org/modelmapper/functional/lambda/TypeMapLambdaTest.java

Lambda api support: map from constant

---

core/src/main/java/org/modelmapper/TypeMap.java
core/src/main/java/org/modelmapper/internal/PropertyReferenceCollector.java
core/src/main/java/org/modelmapper/internal/TypeMapImpl.java
core/src/main/java/org/modelmapper/spi/SourceGetter.java
core/src/main/java/org/modelmapper/spi/TypeSafeSourceGetter.java
core/src/test/java/org/modelmapper/bugs/GH354.java

Reuse the child's TypeMap

---

core/src/main/java/org/modelmapper/internal/MappingContextImpl.java
core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java
core/src/main/java/org/modelmapper/internal/PropertyInfoRegistry.java
core/src/main/java/org/modelmapper/internal/converter/AssignableConverter.java
core/src/main/java/org/modelmapper/internal/converter/CollectionConverter.java
core/src/main/java/org/modelmapper/internal/util/Callable.java
core/src/main/java/org/modelmapper/internal/util/Objects.java
core/src/test/java/org/modelmapper/bugs/GH360.java
core/src/test/java/org/modelmapper/internal/converter/AbstractConverterTest.java

Sorry for this massive commit, that this commit also trying to
refactor the code and cleanup the logic for the mapping engine.
Resolved: #360

Only assigns destination if create by provider

---

core/src/main/java/org/modelmapper/internal/PropertyReferenceCollector.java
core/src/test/java/org/modelmapper/bugs/GH364.java

Resolve method return type correctly

---

core/pom.xml

Fixes OSGi issue

---

core/src/main/java/org/modelmapper/internal/valueaccess/MapValueReader.java
core/src/test/java/org/modelmapper/bugs/GH370.java

Fixes MapValueReader get wrong field type

---

core/src/main/java/org/modelmapper/internal/MappingContextImpl.java
core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java
core/src/main/java/org/modelmapper/internal/util/MappingContextHelper.java
core/src/test/java/org/modelmapper/bugs/GH379.java

Try to resolve the dest generic type from parent

---

core/src/main/java/org/modelmapper/Converter.java
core/src/main/java/org/modelmapper/Converters.java
core/src/test/java/org/modelmapper/bugs/GH248.java

Provides collection converter helper method

---

core/src/main/java/org/modelmapper/convention/NameTransformers.java
core/src/main/java/org/modelmapper/convention/NamingConventions.java
core/src/test/java/org/modelmapper/functional/builder/BuilderTest.java

Support builder pattern

---

core/src/main/java/org/modelmapper/convention/NameTransformers.java
core/src/main/java/org/modelmapper/convention/NamingConventions.java
core/src/test/java/org/modelmapper/functional/builder/BuilderTest.java

Builder supports different prefix

---

core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java
core/src/test/java/org/modelmapper/bugs/GH151.java
core/src/test/java/org/modelmapper/bugs/GH40.java
core/src/test/java/org/modelmapper/functional/NamedTypeMaps.java
core/src/test/java/org/modelmapper/functional/converter/CustomConversion.java

Creates destination after converter.convert

---

.travis.yml
core/src/main/java/org/modelmapper/Converters.java
core/src/test/java/org/modelmapper/bugs/GH389.java
core/src/test/java/org/modelmapper/functional/converter/CollectionFirstElementTest.java

Provides helper function to convert first item of collection

---

core/src/main/java/org/modelmapper/TypeMap.java
core/src/main/java/org/modelmapper/internal/TypeMapImpl.java
core/src/main/java/org/modelmapper/internal/TypeMapStore.java
core/src/main/java/org/modelmapper/internal/util/Objects.java
core/src/test/java/org/modelmapper/bugs/GH182.java

Provides API on TypeMap to support base type mapping

---

core/src/main/java/org/modelmapper/internal/ImplicitMappingBuilder.java
core/src/test/java/org/modelmapper/bugs/GH408.java

Fixed implicit mapping can't map nested property with same type

---

core/src/main/java/org/modelmapper/internal/InheritingConfiguration.java
core/src/test/java/org/modelmapper/internal/InheritingConfigurationTest.java

Fixes: #485 
I fixed configuration mismatches.

Fix configuration 'collectionsMergeEnabled','deepCopyEnabled' (modelmapper#485)

---

core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java

Fix dropping post-converter result

---

core/src/main/java/org/modelmapper/internal/MappingContextImpl.java
core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java
core/src/test/java/org/modelmapper/bugs/GH581.java

Fix wrong cyclic referece detect, we check if the path is matched

---

core/src/main/java/org/modelmapper/internal/converter/MapConverter.java
core/src/main/java/org/modelmapper/internal/util/Maps.java
core/src/test/java/org/modelmapper/bugs/GH550.java

Resolve key value types correctly for map subclasses

---

core/src/main/java/org/modelmapper/builder/ReferenceMapExpression.java
core/src/main/java/org/modelmapper/internal/ConfigurableConditionExpressionImpl.java
core/src/main/java/org/modelmapper/internal/PropertyReferenceCollector.java
core/src/main/java/org/modelmapper/internal/ReferenceMapExpressionImpl.java
core/src/test/java/org/modelmapper/functional/lambda/TypeMapLambdaTest.java

Supports conditional skip `when().skip(src, dest)`

---

extensions/gson/src/main/java/org/modelmapper/gson/JsonElementValueReader.java
extensions/jackson/src/main/java/org/modelmapper/jackson/JsonNodeValueReader.java
extensions/jooq/src/main/java/org/modelmapper/jooq/RecordValueReader.java

Resolve more specific type of value reader

---

core/src/main/java/org/modelmapper/internal/MappingContextImpl.java
core/src/main/java/org/modelmapper/internal/converter/MapConverter.java
core/src/test/java/org/modelmapper/bugs/GH547.java

Keep the generic type info for map's value type

---

core/src/main/java/org/modelmapper/internal/MappingContextImpl.java
core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java
core/src/test/java/org/modelmapper/bugs/GH573.java

Keep the parent source as a chain to have correct src in context

---

core/src/main/java/org/modelmapper/internal/MappingContextImpl.java
core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java
core/src/test/java/org/modelmapper/bugs/GH521.java
core/src/test/java/org/modelmapper/bugs/GH6.java

Create intermediate object depends on if match source found

---

core/src/main/java/org/modelmapper/internal/converter/EnumConverter.java
core/src/test/java/org/modelmapper/internal/converter/EnumConverterTest.java

Fix anonymous enum conversion

---

core/src/main/java/org/modelmapper/internal/PropertyReferenceCollector.java
core/src/test/java/org/modelmapper/bugs/GH608.java

Fix addMappings wrong state when adding multiple mappings

---

core/src/main/java/org/modelmapper/internal/PropertyInfoSetResolver.java
core/src/main/java/org/modelmapper/internal/util/Types.java

Stop looking properties from java internal types

---

core/src/test/java/org/modelmapper/bugs/GH109.java
core/src/test/java/org/modelmapper/bugs/GH204.java
core/src/test/java/org/modelmapper/bugs/GH249.java
core/src/test/java/org/modelmapper/bugs/GH379.java
core/src/test/java/org/modelmapper/bugs/GH38.java
core/src/test/java/org/modelmapper/bugs/GH386.java
core/src/test/java/org/modelmapper/functional/builder/BuilderTest.java
core/src/test/java/org/modelmapper/internal/converter/BooleanConverterTest.java
core/src/test/java/org/modelmapper/internal/converter/NumberConverterTest.java

Fix the order of actual value and expected value in the test code

Fix the order of actual value and expected value in the test code

---

.github/workflows/ci.yml
pom.xml

Bump asm and bytebuddy for java 21 support
